version: '3.3'
services:
  web:
    image: enmai1988/envoked:latest
    depends_on:
      - redis
      - postgres
    ports:
      - 80:3000
    links:
      - postgres
      - redis

  redis:
    image: redis:4.0.1

  postgres:
    image: postgres:9.6.3
    environment:
     POSTGRES_USER: user
     POSTGRES_PASSWORD: password
     POSTGRES_DB: envoked
