export const FETCH_USER_PENDING = 'FETCH_USER_PENDING';
export const FETCH_USER_FULFILLED = 'FETCH_USER_FULFILLED';
export const FETCH_USER_REJECTED = 'FETCH_USER_REJECTED';

export const FETCH_PROJECTS_PENDING = 'FETCH_PROJECTS_PENDING';
export const FETCH_PROJECTS_FULFILLED = 'FETCH_PROJECTS_FULFILLED';
export const FETCH_PROJECTS_REJECTED = 'FETCH_PROJECTS_REJECTED';

export const FETCH_PROJECT_PENDING = 'FETCH_PROJECT_PENDING';
export const FETCH_PROJECT_FULFILLED = 'FETCH_PROJECT_FULFILLED';
export const FETCH_PROJECT_REJECTED = 'FETCH_PROJECT_REJECTED';

export const FORM_SUBMISSION_PENDING = 'FORM_SUBMISSION_PENDING';
export const FORM_SUBMISSION_FULFILLED = 'FORM_SUBMISSION_FULFILLED';
export const FORM_SUBMISSION_REJECTED = 'FORM_SUBMISSION_REJECTED';
export const FORM_SUBMISSION_TEST = 'FORM_SUBMISSION_TEST';
