'use strict';
const express = require('express');
const router = express.Router();
const ProjectController = require('../controllers').Interest;

router.route('/')
  .get(ProjectController.getAll)
;

module.exports = router;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        